title: Envision Portal documentation
description: Just the Envision Portal documentation
theme: just-the-docs

url: https://envision-mods.github.io/docs/

aux_links:
   Envision Portal on GitHub: https://github.com/envision-mods/porfal

# External navigation links
nav_external_links:
  - title: Envision Portal on GitHub
    url: https://github.com/envision-mods/porfal

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
  -
    scope:
      path: "api/classes/EnvisionPortal"
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      parent: API

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/envision-mods/docs" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

plugins:
  - jekyll-optional-front-matter
